# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: 'https://filip-f.github.io/'
email: f.francet@hotmail.com
author: Filip Francetic
description: "Filip Francetic's personal website"
header-img: 'img/filip.jpg'
copyright: 'Copyright &copy; 2018 Filip Francetic.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/Filip-F
    icon: github
  - title: linkedin
    url: https://www.linkedin.com/in/filipfrancetic/
    icon: linkedin
  - title: resume
    icon: file
    url: pdf/FilipFranceticResume.pdf

email: ffrancet@edu.uwaterloo.ca
